version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: empleados_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-service:
    build: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
      empleados-service:
        condition: service_started
      asistencia-service:
        condition: service_started
      evaluacion-service:
        condition: service_started

  empleados-service:
    build: ./empleados-service
    expose:
      - "8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/empleados_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy

  asistencia-service:
    build: ./asistencia-service
    expose:
      - "8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/empleados_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
      empleados-service:
        condition: service_started

  evaluacion-service:
    build: ./evaluacion-service
    expose:
      - "8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/empleados_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
      empleados-service:
        condition: service_started

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      gateway-service:
        condition: service_started

volumes:
  mysql_data: 